### PR TITLE
feat: Support Moore Threads GPU

### PR DESCRIPTION
**Pull request by yeahdongcn**
Since [pull request #8383](https://github.com/ggerganov/llama.cpp/pull/8383) has been merged into [llama.cpp](https://github.com/ggerganov/llama.cpp), I would like to add MTGPU support to GPUStack. This PR might be the first step towards that goal.

### CODE REVIEW

**Comment by thxCode** [comment]
Thanks.

I am happy to see this. GPUStack is based on https://github.com/gpustack/llama-box, and I tried to compile a distribution for MT, see https://github.com/gpustack/llama-box/commit/0907d661bf98e6a74a446e16a8dccdffe7face80.

But it failed. If you can, please fix the llama-box. After llama-box generates the MT version correctly, I will approve this and go ahead.

**Comment by yeahdongcn** [comment]
> Thanks.
> 
> I am happy to see this. GPUStack is based on https://github.com/gpustack/llama-box, and I tried to compile a distribution for MT, see [gpustack/llama-box@0907d66](https://github.com/gpustack/llama-box/commit/0907d661bf98e6a74a446e16a8dccdffe7face80).
> 
> But it failed. If you can, please fix the llama-box. After llama-box generates the MT version correctly, I will approve this and go ahead.


Sure! Here's a refined version of your GitHub comment:

That sounds reasonable. I can assist with that.

**Comment by yeahdongcn** [comment]
It seems that yesterday's CI failure is unrelated to this PR (`fastfetch` was mistakenly sourced from a fork).

**Comment by yeahdongcn** [comment]
@thxCode Could you approve the workflows? Thanks.

**Comment by yeahdongcn** [comment]
Yes, I've already started on this. As mentioned in the PR description, this is the very first step, which is why I've marked MTGPU in the future support list.

**Comment by CarterLi** [comment]
@yeahdongcn Does MT driver implement all the same userland APIs as NV's, including CUDA and NVML?

**Comment by aiwantaozi** [comment]
@yeahdongcn The new feature you're proposing is indeed valuable. Before we can merge the PR into GPUStack, need to ensure its dependencies (fastfetch and llama-box) are working correctly.

Once the dependencies are verified, we will promptly revisit and merge your PR.

**Comment by yeahdongcn** [comment]
> @yeahdongcn Does MT driver implement all the same userland APIs as NV's, including CUDA and NVML?

Not exactly the same, but similar.

**Comment by CarterLi** [comment]
> > @yeahdongcn Does MT driver implement all the same userland APIs as NV's, including CUDA and NVML?
> 
> Not exactly the same, but similar.

Will Old Huang sue you?

**Comment by yeahdongcn** [comment]
See https://github.com/gpustack/fastfetch/pull/2 for `fastfetch` changes.

**Comment by yeahdongcn** [comment]
> > > @yeahdongcn Does MT driver implement all the same userland APIs as NV's, including CUDA and NVML?
> > 
> > 
> > Not exactly the same, but similar.
> 
> ~Will Old Huang sue you?~
> 
> Just kidding

Haha, you might want to check how HIP did it.

**Comment by CarterLi** [comment]
@yeahdongcn I think MT provides the same APIs on Windows as what it does on Linux. The fastfetch part can be ported to Windows easily, right?

@aiwantaozi The current way of GPU detection on Windows is kinda unfriendly for non-Nvidia GPUs. I have solved the multi-gpu issue in the official fastfetch repo ( still needs more testing though ). You may backport it to your fork repo.

https://github.com/fastfetch-cli/fastfetch/blob/884fd097c61933bd441ed3ea65c8d3f4797c3bf8/src/detection/gpu/gpu_windows.c#L152-L180

**Comment by yeahdongcn** [comment]
> @yeahdongcn I think MT provides the same APIs on Windows as what it does on Linux. The fastfetch part can be ported to Windows easily, right?
> 
> @aiwantaozi The current way of GPU detection on Windows is kinda unfriendly for non-Nvidia GPUs. I have solved the multi-gpu issue in the official fastfetch repo ( still needs more testing though ). You may backport it to your fork repo.
> 
> https://github.com/fastfetch-cli/fastfetch/blob/884fd097c61933bd441ed3ea65c8d3f4797c3bf8/src/detection/gpu/gpu_windows.c#L152-L180

Yeah, but I'm afraid I'm not a Windows guy. Setting up a Windows environment is killing me.

**Comment by aiwantaozi** [comment]
@CarterLi ca
Due to time constraints, we haven't had a chance to report and fix bugs upstream yet. We are very grateful to you and your project for the significant help. Since GPUStack will run as a Windows Service, we cannot obtain device information through EnumDisplayDevicesW when running as a Windows Service. Therefore, we made some temporary modifications. We would greatly appreciate any suggestions you might have. Thank you!

**Comment by aiwantaozi** [comment]
@yeahdongcn 
Hi,
fastfetch has released 2.18.1.5, could you please update and check if it works with GPUStack?

After updating the version [here](https://github.com/gpustack/gpustack/blob/1d727f1bd4d590981af04a0ba3e94cbfdf4420d1/hack/install.sh#L22), could follow the [development doc](https://docs.gpustack.ai/development/?h=). Thanks.

**Comment by CarterLi** [comment]
> Since GPUStack will run as a Windows Service, we cannot obtain device information through EnumDisplayDevicesW when running as a Windows Service. Therefore, we made some temporary modifications. We would greatly appreciate any suggestions you might have. Thank you!

In this case, you may enumerate PCI devices by enumerating `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Enum\PCI` or setupapi.

Note: not every GPU uses PCI bus. Notably Apple Silicon

**Comment by aiwantaozi** [comment]
@CarterLi Thank you for your fantastic suggestions! Will try to get GPU info from Windows registry.

**Comment by CarterLi** [comment]
Upstream now uses SetupAPI to fetch GPU devices. It should work when running as a Windows Service ( untested though ) https://github.com/fastfetch-cli/fastfetch/commit/0354fd5d9de1d70778cbd3e16778511ec4f5d372

I suggest you move back to upstream, instead of maintaining a dirty and outdated fork. If you encounter any bug you can either open PR to fix it, or just file it upstream and I will look at it.

The only one upstream is missing is UUID, which is unnecessary IIRC. We have `FFGPUResult::deviceId`. It's `AdapterLuid` on Windows and bus address on Linux, both should not change.

**Comment by yeahdongcn** [comment]
> @yeahdongcn Hi, fastfetch has released 2.18.1.5, could you please update and check if it works with GPUStack?
> 
> After updating the version [here](https://github.com/gpustack/gpustack/blob/1d727f1bd4d590981af04a0ba3e94cbfdf4420d1/hack/install.sh#L22), could follow the [development doc](https://docs.gpustack.ai/development/?h=) here to run. Thanks.

It looks good after switching fastfetch to my local build (with [PR #3](https://github.com/gpustack/fastfetch/pull/3)). Please see the screenshot below.

Screenshot 2024-08-03 at 22 24 29

One notable issue is that our MTML library currently has no interface to query the number of cores. I have opened a JIRA ticket internally and will make another change to fix this.

**Review by aiwantaozi — APPROVED** [review]
LGTM

**Pull request merged**
